NodeJS server gives static files
frontend-park-mail-ru/2019_2_IBAT pull request #1
Opened 2019-09-06 13:22 UTC by vladimirsukiasyan

2019-09-06 13:22 UTC, vladimirsukiasyan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Отдача статики на nodejs](https://trello.com/c/hRR1T5DT/2-%D0%BE%D1%82%D0%B4%D0%B0%D1%87%D0%B0-%D1%81%D1%82%D0%B0%D1%82%D0%B8%D0%BA%D0%B8-%D0%BD%D0%B0-nodejs)

2019-09-06 13:42 UTC, SinimaWath requested changes

2019-09-06 13:42 UTC, SinimaWath commented on server.js
> +  res.sendFile(__dirname + '/public/index.html', (err) => {
А если не index.html? А другие файлики, у нас же будет сейчас много страничек

2019-09-06 13:46 UTC, vladimirsukiasyan commented on server.js
> +  res.sendFile(__dirname + '/public/index.html', (err) => {
Другую статику получаем через имя файла, к примеру hostname:port/about.html
express.static позволяет отдавать статику по пути

2019-09-06 14:00 UTC, SinimaWath commented on server.js
> +app.use(express.static(__dirname + '/public'));
Ладно тогда давай сделаем отдельную переменную public, в которой будет путь до паблик и используй ее

2019-09-06 14:00 UTC, SinimaWath commented on server.js
> +  res.sendFile(__dirname + '/public/index.html', (err) => {
Да, ты прав )

2019-09-06 14:03 UTC, SinimaWath commented
Давай вынесем server.js в папку server. Давай из гитигнора уберем папку public. А в gitignore добавим потом папку build, в которой будем держать приложение

2019-09-07 10:36 UTC, SinimaWath approved these changes
Хорошо

2019-09-07 10:36 UTC, merged