на ревью
frontend-park-mail-ru/2019_2_IBAT pull request #3
Opened 2019-09-08 14:46 UTC by moguchev

2019-09-08 15:42 UTC, moguchev commented
![](https://github.trello.services/images/mini-trello-icon.png) [Верстка](https://trello.com/c/mF7a5HFc/4-%D0%B2%D0%B5%D1%80%D1%81%D1%82%D0%BA%D0%B0)

2019-09-08 16:21 UTC, SinimaWath requested changes
Сделайти кнопки перехода на регистрацию, авторизацию, на главное странице

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +    <title>IBAT</title>
может не IBAT? У каждой страницы должен быть свой title. Тут это Создание резюме. Можешь не исправлять, но в след. раз учти

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                <div class="menu">
это же nav тэг

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                <div class="menu">
или в крайнем случае ul

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                    <div class="fill"></div>
Не надо так. Если хочешь сделать пробел. Оберни в 2 div и еще c помощью флексбокса сделай

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                <a class="logo" href="/index.html">
Сделай всем a элементам focus стили, как у инпутов

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                            <span class="form_span">Имя</span>
для этого есть тэг label

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                            <input placeholder="Имя" type="text" class="bloko-input">
Всегда должен быть первый инпут активный

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                            <input placeholder="+7" type="text" class="bloko-input">
Для этого есть нормальный тип в html5 tel 
https://www.w3schools.com/html/html_form_input_types.asp

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                                    <input name="birthday[0].date" data-qa="resume__birthday__day" data-name="birthday[0].date.day" type="text" maxlength="2" placeholder="День" class="bloko-input blo
какой интересный name ) Зачем он нужен? data-qa - у нас че появились end-to-end тесты?

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +                            <textarea name="skills[0].string" placeholder="Расскажите о своих качествах, знаниях, увлечениях, которые, как вам кажется, будут полезны работодателю" class="bloko-textar
что такое skills?

2019-09-08 16:21 UTC, SinimaWath commented on public/css/base.css
> +html, body, div, span, table, tbody, thead, tfoot, tr, td, hr, br, p, em, abbr, strong, small, h1, h2, h3, h4, h5, h6, img, sub, sup, dl, dt, dd, ol, ul, li, fieldset, form, label, legend, iframe, ob
Давай не reset.css, а normalize.css

2019-09-08 16:21 UTC, SinimaWath commented on public/css/base.css
> +.container {
Стили никуда не годятся, давай читать про БЭМ, разделять стили на блоки и компоненты. CSS не так просто как кажется, тут тоже нужно саблюдать паттерны ) https://ru.bem.info/methodology/quick-start/

2019-09-08 16:21 UTC, SinimaWath commented on public/css/base.css
> +    -ms-user-select: none;
Знаешь что значит -ms?

2019-09-08 16:21 UTC, SinimaWath commented on public/css/base.css
> +    transition: background-color .2s ease-in-out, color .2s ease-in-out, box-shadow .2s ease-in-out;
Ты точно знаешь про transition? Или просто спиздил?

2019-09-08 16:21 UTC, SinimaWath commented on public/css/base.css
> +    -webkit-tap-highlight-color: transparent;
А это зачем?

2019-09-08 16:21 UTC, SinimaWath commented on public/css/base.css
> +.form-row-input {
Где он вообще используется?

2019-09-08 16:21 UTC, SinimaWath commented on public/employeeprofile.html
> +    <link rel="stylesheet" href="css/base.css"/>
У каждой страницы свой css

2019-09-08 16:21 UTC, SinimaWath commented on public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
Знаешь зачем нужны эти 3 meta строчки?

2019-09-08 16:21 UTC, SinimaWath commented on public/login.html
> +
?

2019-09-08 16:21 UTC, SinimaWath commented on public/login.html
> +                        <buttom>Соискателя</buttom>
buttom?

2019-09-08 16:21 UTC, SinimaWath commented on public/login.html
> +<html lang="en">
Как перейти на эту страницу?

2019-09-08 16:21 UTC, SinimaWath commented on public/login.html
> +    <div class="wrapper">
Сделай эту страницу по дизайну, как создание резюме, только сам и не пизди стили )

2019-09-08 16:21 UTC, SinimaWath commented on public/signupemploee.html
> +<body>
Сделай тоже как Создание резюме по стилю

2019-09-08 16:21 UTC, SinimaWath commented on public/vacancy.html
> +<body>
Убери все что напиздили: ненужные стили, атрибуты, непонятную мету, которую не знаешь

2019-09-08 16:21 UTC, SinimaWath commented on public/createresume.html
> +<html lang="en">
У нас все на русском, а lang = en )  Непорядок

2019-09-10 12:12 UTC, SinimaWath requested changes

2019-09-10 12:12 UTC, SinimaWath commented on public/css/header.css
> +.block-button {
У вас есть блок button. Так что назовите его button, и а в header, у вас есть header__button

2019-09-10 12:12 UTC, SinimaWath commented on public/css/header.css
> +.block-button__blue {
button_blue

2019-09-10 12:12 UTC, SinimaWath commented on public/css/header.css
> +.block-button__blue {
Это модификатор

2019-09-10 12:12 UTC, SinimaWath commented on public/css/header.css
> +.supernova-button {
button button_supernova header__button - вот такие стили должны быть у кнопки. Прочитайте про модификаторы БЭМ

2019-09-10 12:12 UTC, SinimaWath commented on public/css/header.css
> +.supernova-button {
Тут все стили почти из button

2019-09-10 12:12 UTC, SinimaWath commented on public/header.html
> +        <div class="menu header__menu">
nav

2019-09-10 12:12 UTC, SinimaWath commented on public/header.html
> +                <span class="icon-profile"></span>
profile__icon

2019-09-10 17:34 UTC, SinimaWath commented on public/header.html
> +            <input class="block-input search-form__search" type="text" placeholder="Поиск" name="s">
опять же, input search-form_input

2019-09-16 14:50 UTC, merged