Added ResumePage and list of resumes
frontend-park-mail-ru/2019_2_IBAT pull request #8
Opened 2019-10-07 20:44 UTC by vladimirsukiasyan

2019-10-07 20:45 UTC, vladimirsukiasyan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Добавить страницу резюме и список резюме](https://trello.com/c/xdMGyT0s/39-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%83-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5-%D0%B8-%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%80%D0%B5%D0%B7%D1%8E%D0%BC%D0%B5)

2019-10-08 17:56 UTC, SinimaWath requested changes

2019-10-08 17:56 UTC, SinimaWath commented on package.json
> +    "eslint": "./node_modules/eslint/bin/eslint.js"
Добавьте еще команду lint:fix.

2019-10-08 17:56 UTC, SinimaWath commented on package.json
> +    "*.{js, jsx}": [
jsx? Зачем?

2019-10-08 17:56 UTC, SinimaWath commented on .eslintrc
> +    "jsx-quotes": [1, "prefer-double"]
У вас же нет jsx

2019-10-08 17:56 UTC, SinimaWath commented on public/css/base.css
> +    margin: 15px 0px;
Можно написать 15px 0 так экономишь байты

2019-10-08 17:56 UTC, SinimaWath commented on public/css/card_list.css
>      padding: 15px;
Зачем pt? Почему не rem, em или vh или vw или px?

2019-10-08 17:56 UTC, SinimaWath commented on public/js/views/Index/IndexView.js
> +      for (const [resumeId, resume] of Object.entries(resumes)) {
Давай без for

2019-10-08 17:56 UTC, SinimaWath commented on public/js/application.js
>    const globalEventBus = new EventBus([
Почему бы его не сделать синглтоном? И везде использовать инстанс через import?

2019-10-12 00:19 UTC, merged